baseURL = "http://jwetzell.com/"
languageCode = "en-us"
title = "Joel Wetzell"
theme = "KeepIt"


[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

[params]
    since = 2016
    author = "Joel Wetzell"               # Author's name
    subtitle = "Just some side projects"       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    avatar = "/images/me/avatar.jpg" #comment it to use gravatar
    socialShare = true

    description = "Joel Wetzell's portofolio site" # site description
    keywords = "" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.social]
    GitHub = "jwetzell"
    Linkedin = "joel-wetzell-81975979"
    Twitter = "jwetzell"
    Instagram = "jwetzell"
    Facebook = "joel.wetzell"
    Gitlab = "jwetzell"
    Reddit = "imhonestlyconfused"
    Paypal = "JoelWetzell"

[params.share]
    Twitter = true
    Facebook = true
    Linkedin = true

# Used only for Seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Joel Wetzell"
