baseURL = "http://jwetzell.com/"
languageCode = "en-us"
title = "Joel Wetzell"
theme = "KeepIt"


[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

[params]
    since = 2016
    author = "Joel Wetzell"               # Author's name
    subtitle = "Just some side projects"       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    avatar = "/images/me/avatar.jpg" #comment it to use gravatar
    socialShare = true

    description = "Joel Wetzell's portofolio site" # site description
    keywords = "" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.social]
    GitHub = "jwetzell"
    Linkedin = "xxxx"
    Twitter = "jwetzell"
    #Instagram = "jwetzell"
    #Email   = "xxxx"
    Facebook = "joel.wetzell"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    Gitlab = "jwetzell"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    Paypal = "JoelWetzell"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

[params.share]
    Twitter = true
    Facebook = true
    #Reddit = true
    Linkedin = true
    #Pinterest = true
    #HackerNews = true
    #Mix = true
    #Tumblr = true
    #VKontakte = true
    #Douban = true
    #Weibo = true

# Used only for Seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Joel Wetzell"
