name: publish
on:
  push:
    branches:
      - master
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          submodules: "recursive"
      - name: setup hugo
        uses: peaceiris/actions-hugo@v3.2.1
        with:
          hugo-version: "0.163.0"
          extended: true
      - name: build
        run: hugo --minify --destination ./build

      - name: publish
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./build/
          port: 21
          protocol: ftps
